name: Build docs

on:
    push:
        branches:
            - master

jobs:
    sphinx_docs_to_gh-pages:
        name: Sphinx docs to gh-pages
        runs-on: ubuntu-latest

        permissions:
            contents: write
            pages: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip wheel
                  pip install -e ".[docs]"
            - name: Install package
              run: |
                python -m pip install -vv --no-build-isolation .
            - name: Running the Sphinx to gh-pages Action
              uses: uibcdf/action-sphinx-docs-to-gh-pages@v2.1.0
              with:
                  branch: master
                  dir_docs: docs
                  sphinx-apidoc-opts: "--separate -o . ../"
                  sphinx-apidoc-exclude: ""
                  sphinx-opts: ""
