name: Test

on:
    push:
        # Push events to master with version tags, e.g. "v1.0"
        branches: [master]
        tags:
            - "v**"
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ${{ matrix.os }}

        defaults:
            run:
                # -e to fail on error
                shell: bash -e {0}

        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.9", "3.10", "3.11"]
                os: [ubuntu-latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: "pip"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip wheel
                  pip install -e ".[test]"
            - name: Test
              run: |
                  pytest -v --cov --color=yes --cov-report=xml
                  pytest --color=yes --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
